### ISSUE TITLE
Name des Repos ändern

### ISSUE THREAD

**Issue by LMazzole** [HSR-Stud/Physik-2#1]
Ich empfehle den Namen des Repos auf Physik2HS18 zu ändern um Verwechslungen mit anderen Repos zu vermeiden.

**Comment by dav1d-wright** [comment]
Ich würde keine Jahreszahl im Namen haben, da dieses Repo ja viel länger leben sollte. "HS18" wäre meiner Meinung nach eher eine Version, also ein Tag. 
Ich habe jedoch gesehen, dass es gar kein anderes Ph2 Repo gibt, oder liege ich da falsch?

**Comment by LMazzole** [comment]
@wrd90 Nein da liegst du richtig. Die Idee mit den Tags funktioniert natürlich auch. Ein komplett neues Repo wird ja eigentlich erst nötig, sobald der Dozent wechselt.   
Es gibt halt immer wieder Studenten, welche eine neue Formelsammlung schreiben wollen, daher bringt meiner Meinung nach der Zusatz des Semesters, in welcher das Repo erstellt wurde eine bessere Übersicht.

**Comment by dav1d-wright** [comment]
@LMazzole hmm das würde aber meiner Meinung nach die Idee des kollaborativen Arbeiten an den Zusammenfassungen ein wenig kippen. Falls das aber jemand machen möchte würde ich sagen wäre ein neuer Branch eher angebracht als ein komplett neues Repo.

**Comment by LMazzole** [comment]
@wrd90 Das ist richtig.  Aber viele Studenten sind hier das erste mal in Kontakt mit LaTeX und Git, daher erachte ich es als Sinnvoll den Einstieg so einfach wie möglich zu halten. Das Arbeiten mit unterschiedlichen Branches erhöht hier die Schwierigkeit.  
Ich glaube wir müssen hier einen Grundsatzentscheid fällen wie wir das zukünftig handhaben wollen.  
@pescara deine Meinung?

**Comment by Dev4Future** [comment]
Da es noch keine ander Ph2 Zusammenfassung gibt, würde ich es nach dem Modul benennen. Entweder Ph2HAT oder vereinfacht Ph2. Dasselbe mit Phy1 zu Ph1 oder Modulname, damit Sie einheitlich benannt werden. Neue, stark abweichende Repos, wie im Willkommensrepo beschrieben.

**Comment by Dev4Future** [comment]
@LMazzole @wrd90 kann ich Physik-2 und Phy1 einheitlich umbenennen?

**Comment by dav1d-wright** [comment]
@Dev4Future sorry für die verspätete Antwort. Ja, meiner Meinung nach kannst du sie umbenennen.
